apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      containers:
        - name: autoscaler
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
