apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8scaler.fullname" . }}
  labels:
    app: {{ include "k8scaler.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8scaler.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8scaler.name" . }}
    spec:
      serviceAccountName: {{ include "k8scaler.serviceAccountName" . }}
      containers:
        - name: autoscaler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
